### ISSUE TITLE
Issues when using DISTINCT

### ISSUE THREAD

**Issue by pejrich** [mojotech/scrivener_ecto#11]
I have an autocomplete route. Here's the model code.
```

def search_by_name(query) when is_binary(query) do
    from r in Room, where: ilike(r.name, ^"%#{query}%")
  end
```

My design allows rooms with the same name, obviously only want distinct names for autocomplete, so I change the query to:
```

def search_by_name(query) when is_binary(query) do
    from r in Room, where: ilike(r.name, ^"%#{query}%"), distinct: r.name
  end
```

This causes an error.
```

** (Postgrex.Error) ERROR (grouping_error): column "r0.name" must appear in the GROUP BY clause or be used in an aggregate function
[debug] QUERY ERROR db=0.7ms
SELECT DISTINCT ON (r0."name") count(DISTINCT r0."id") FROM "rooms" AS r0 WHERE (r0."name" ILIKE $1) ["%Go%"]
```

The error only occurs when trying to paginate. If I grab all the entries with `Repo.all`, there are no issues.

**Comment by drewolson** [comment]
I'll take a look this weekend. Can you provide a failing test?

**Comment by drewolson** [comment]
62681ff73954846370ee41047d0a349c530b3d8b should fix this.
