### ISSUE TITLE
Changelog changes are not picked up on hex

### ISSUE THREAD

**Issue by idabmat** [mojotech/scrivener_ecto#113]
Thanks to the new maintainers for picking this project back up.

I might be missing something but found it odd not to see the changes in the changelog in https://diff.hex.pm/diff/scrivener_ecto/3.0.0..3.1.0 Especially since I can see it was updated here in GitHub. Not sure why that is, but just wanted to flag it here as hexdiff is a great when doing dependencies update.

**Comment by cpjolicoeur** [comment]
@idabmat thanks for reporting thing
