### ISSUE TITLE
Ecto.NoResultsError on Repo.paginate

### ISSUE THREAD

**Issue by mkaszubowski** [mojotech/scrivener_ecto#12]
I'm using `Repo.paginate(query)`.  Because the lib uses `Repo.one!`, it throws `(Ecto.NoResultsError) expected at least one result but got none in query:` if there are no results.
I think it would be helpful if this would return either empty page or `{:error, :something}` tuple. `Repo.paginate!` could be added with the current behaviour. 

Please let me know what you think about it, I can submit a PR if you agree.

**Comment by drewolson** [comment]
This is a good idea, though it'll involved major releases for both Scrivener and Scrivener.Ecto. Let me take a crack at it in the next week or two.

**Comment by drewolson** [comment]
Fixed in `1.0.3`.
