### ISSUE TITLE
Table with no Primary Key failed paginater

### ISSUE THREAD

**Issue by ardhitama** [mojotech/scrivener_ecto#14]
I have a table with no PK, caused
```
** (exit) an exception was raised:
    ** (ArgumentError) argument error
        :erlang.hd([])
        lib/scrivener/paginater/ecto/query.ex:35: Scrivener.Paginater.Ecto.Query.total_entries/2
        lib/scrivener/paginater/ecto/query.ex:10: Scrivener.Paginater.Ecto.Query.paginate/2
```

Offending code
```
defp total_entries(query, repo) do
    primary_key =
      query.from
      |> elem(1)
      |> apply(:__schema__, [:primary_key])
      |> hd
```

Already marked the schema with `@primary_key false`

**Comment by drewolson** [comment]
@ardhitama I'm not sure how to deal with both joinable data and a table without primary keys. I'll look into it. Can you provide a failing test?

**Comment by felipegasparini** [comment]
Hi @drewolson,  I'm having the same issue.

You can test it by adding a "@primary_key false" in any schema definition that you already have. Ex:

```  
 @primary_key false
  schema "user" do
    field :name, :string
    field :email, :string
  end
```

I have one question: Why can't you use a count(*) instead of count(distinct primary_key)?

Something like this: https://github.com/felipegasparini/scrivener_ecto/commit/7ec1548de24e13774ddbf07cc82620d485f0fb6c

**Comment by felipegasparini** [comment]
Btw, a good thing about not using the schema at all is that now the scrivener will also work with schemaless queries in Ecto: 

```
Repo.paginate(from "posts", select: [:title, :body]) 
```

**Comment by drewolson** [comment]
[This gist](https://gist.github.com/drewolson/0378375ef119858eca1e8564b17984f9) shows the test that fails if we move back to counting via `*`.

Specifically, we can no longer correctly support `group_by` clauses demonstrated by [this test](https://github.com/drewolson/scrivener_ecto/blob/46243f10193cf2cbd160f11a97b68db22a6fbba2/test/scrivener/paginator/ecto/query_test.exs#L135-L145).

**Comment by drewolson** [comment]
I'd be open to other ways of solve this problem and removing the dependency on the schema, but we need to figure out what to do regarding the `group_by` queries.

**Comment by drewolson** [comment]
62681ff73954846370ee41047d0a349c530b3d8b should fix this.
