### ISSUE TITLE
** (Mix) No package with name scrivener_ecto (from: mix.exs) in registry

### ISSUE THREAD

**Issue by feixionglee** [mojotech/scrivener_ecto#2]
got a error.  **(Mix) No package with name scrivener_ecto (from: mix.exs) in registry** 

```
defp deps do
  [..., 
  {:scrivener_ecto, "~> 1.0"},
  ...]
end
```

then run  `mix deps.get`

**Comment by drewolson** [comment]
@feixionglee The package has not been released on hex yet (I'm waiting for the release of Ecto 2.0). For now, please use a github dependency.
