### ISSUE TITLE
Mongo doesn't support subqueries 

### ISSUE THREAD

**Issue by merqlove** [mojotech/scrivener_ecto#21]
Subj

**Comment by drewolson** [comment]
Ecto 2.0 (required by this library) does not support Mongo.

**Comment by merqlove** [comment]
Maybe  better is to make total pages counter customizable? For example through repo or config.

**Comment by merqlove** [comment]
It's support will be enabled soon.

**Comment by drewolson** [comment]
At that time it may be better to create a new scrivener library to support Mongo specifically.

**Comment by merqlove** [comment]
👍 Maybe, ok I will fix 'kerosene' now, seems that they don't use subqueries. 1 line fix :)
