### ISSUE TITLE
Avoid OFFSET when possible

### ISSUE THREAD

**Issue by vhf** [mojotech/scrivener_ecto#25]
(Following up on #20 )

Detecting if there's an `order_by` and using a combination of `WHERE pk > :last_id` and `LIMIT :page_size` seems like a good approach.

What do you think?

**Comment by drewolson** [comment]
@vhf this only works if the schema is using an integer-based, ascending primary id. It wouldn't work for applications using, say, UUIDs as identifiers. I think cursor-based pagination is a great approach, but I think it should live in a separate, specific repo that implements the `Scrivener.Paginator` protocol with this new technique.

**Comment by joshuataylor** [comment]
@drewolson - Do you think this should be a separate module, or included within scrivener_ecto?

I'm interested in helping with this, and would be happy to contribute back code for this.

**Comment by drewolson** [comment]
Because these changes will effectively be backwards incompatible, I'd like
them to be in a separate module. I will happily link to it from the
scrivener readme if it turns out well.
