### ISSUE TITLE
Elixir 1.2 not compatible with ecto 2.1+

### ISSUE THREAD

**Issue by stephenmoloney** [mojotech/scrivener_ecto#30]
#### Issue:
Ecto 2.1.x - Incompatible with elixir 1.2

https://github.com/elixir-ecto/ecto/blob/v2.1/CHANGELOG.md

I'm setup a build matrix on travis.yml and I'm getting the following error when using 
```
    - otp_release: 18.3
      elixir: 1.2
```

`warning: the dependency :ecto requires Elixir "~> 1.3" but you are running on v1.2.6`

https://travis-ci.org/stephenmoloney/scrivener_list/builds/233549003

Potential solutions:

1. Add a warning to readme.md about potential issue and to fix ecto manually if using old elixir.
2. Up version of elixir required to use scrivener_ecto to `1.3`
3. Fix ecto at 2.0 --- not a good idea :-1:

**Comment by drewolson** [comment]
Thanks @stephenmoloney. I'll take a look at this in a few days. I'll probably just updated the required elixir version to 1.3, unless there are a lot of folks against this idea.

**Comment by drewolson** [comment]
Fixed in https://github.com/drewolson/scrivener_ecto/commit/63bcc107c5d3970416f70dc0bc6b93f0921c9f78

Thanks for the report!
