### ISSUE TITLE
pagination should respect the order_by clause across all pages

### ISSUE THREAD

**Issue by egeersoz** [mojotech/scrivener_ecto#31]
As things stand, the `order_by` clause seems to be run on each individual page.

This is highly problematic. For example, if you try to implement a reddit-style post ordering whereby posts are ordered by vote count, the first result on the second page will potentially have a higher vote count than the last result on the first page.

Example dataset:

```
Post1 - 3 votes
Post2 - 2 votes
Post3 - 4 votes
Post4 - 5 votes
Post5 - 1 vote
Post6 - 6 votes
```

Example query with `page_size: 3`:

```
def list_posts(params)
  query =
    from p in Post,
    left_join: v in assoc(p, :votes),
    order_by: [desc: count(v.id)],
    group_by: p.id,
    select: p

  Repo.all(query)
end
```

This returns the results in the correct order. 

```
Post6 - 6 votes
Post4 - 5 votes
Post3 - 4 votes
Post1 - 3 votes
Post2 - 2 votes
Post5 - 1 vote
```

But if I replace `Repo.all` with `Repo.paginate(query, params)`, the sort order breaks. Page 1 ends up having:

```
Post3 - 4 votes
Post1 - 3 votes
Post2 - 2 votes
```

And page 2 ends up having:

```
Post6 - 6 votes
Post4 - 5 votes
Post5 - 1 vote
```

So it looks like Scrivener gets the first 3 results for page 1, and the next 3 results for page 2, and so on. This causes the `order_by` clause to run only across each page's results, which severely limits the usefulness of this library.

Perhaps a `pre_order` option is needed whereby `paginate` grabs all results and then paginates them internally.

**Comment by dsignr** [comment]
sorry to wake up a 2 year old issue. This is still an issue as of 2020 and I wonder why this was closed. Has this been resolved (genuinely curious to see if it's an issue on my end)?
