### ISSUE TITLE
pagination in case of many to many

### ISSUE THREAD

**Issue by newterminator** [mojotech/scrivener_ecto#33]
I have **post** `many_to_many :tags, MyApp.Tag, join_through: MyApp.PostTag`

and **tag** `many_to_many :posts, MyApp.Post, join_through: MyApp.PostTag` 

I am trying to list and paginate all the posts that have been tagged with a particular tag.
In the posts controller I have: 
```elixir
def tag_index(conn, params) do
    page = Tag
          |> where([t], t.tag_name == ^params["tag_name"])
          |> preload(posts: :user)
          |> Repo.paginate(params)

    render(conn, "tag_index.html", tag: page.entries, page: page)
end
```
In the tag_index.html I have: 
```
<%= for post <- @tag.posts do %>
    <%= render "_index_content.html", post: post, conn: @conn %>
<% end %>

<%= if @page.page_number > 1 do %>
    <%= link "Prev Page", to: post_path(@conn, :tag_index, @tag.tag_name %>
<% end %>
<%= if @page.page_number < @page.total_pages do %>
    <%= link "Next Page", to: post_path(@conn, :tag_index, @tag.tag_name %>
<% end %>
```
The above causes an `(ArgumentError) argument error` for the line `<%= for post <- @tag.posts do %>`. I debugged and saw that page.entries is properly loaded and all the page.entries and total_entries and all. But doing `@tag.posts` does not work. Any help in rectifying this issue will be appreciated.

Using Phoenix 1.2.0
Elixir 1.4.2
Scrivener_ecto:1.2.1

**Comment by drewolson** [comment]
@newterminator the `page.entries` field returns a list of entries. You are attempting to treat it as a struct by accessing the `.posts` field, which does not exist on a list.

**Comment by newterminator** [comment]
@drewolson Thanks for getting back, your comment helped in realizing and resolving the issue. Cheers.
