### ISSUE TITLE
Dialyzer complains of unknown functions

### ISSUE THREAD

**Issue by ghost** [mojotech/scrivener_ecto#34]
Dialyzer is raising the following complaints:

```
:0: Unknown function 'Elixir.Scrivener':paginate/2
:0: Unknown function 'Elixir.Scrivener.Config':new/3
```

**Comment by drewolson** [comment]
Thanks for the report. I'm not much of a dialyzer expert myself and I'm mostly using the current `@spec`s for documentation purposes. I'd love a hand in fixing these issues.

**Comment by jeremyowensboggs** [comment]
When running `mix dialyzer` on this project, I do not see those errors.  I also don't see those methods, so in essence, I would agree with the errors presented are indeed real errors, and not a mistake.
