### ISSUE TITLE
Upgrade to use newer ecto

### ISSUE THREAD

**Issue by AaronVasquez** [mojotech/scrivener_ecto#36]
Can we upgrade this to use ecto ~>2.1.0

**Comment by drewolson** [comment]
This should work fine with ecto 2.1 considering we're specifying the dependency with `~> 2.0`. Are you seeing issues?

**Comment by AaronVasquez** [comment]
Looked into it more. Another dependency (ex_admin) is having problems with 2.1, thought it was scrivener. Nvm.
