### ISSUE TITLE
Does Scrivener Support Ecto Prefixes?

### ISSUE THREAD

**Issue by brandonparsons** [mojotech/scrivener_ecto#41]
Good morning,

Was just giving Scrivener a shot, and it's not immediately obvious to me how to get it to use Ecto's `prefix` option in the queries it builds.

Am I missing something or is this not supported?

Thanks!

**Comment by drewolson** [comment]
Scrivener itself supports an `options` key that allows an arbitrary keyword value. Perhaps we could add support for using `prefix` inside `options` from Scrivener.Ecto?

**Comment by brandonparsons** [comment]
I looked into this a bit more, and you may run into trouble using prefixes as you utilize a subquery to get at the count. I'm too new to all this to know if there's a workaround or not :)

**Comment by edipox** [comment]
Hi @brandonparsons 
I was looking at the existing issues here. 
Now `Scrivener.Ecto` supports a `total_entries` option, so you can implement your own code to get the total entries and avoid using the subquery `count`.
For example: 
```elixir
      config = %Scrivener.Config{
        module: Scrivener.Ecto.Repo,
        page_number: 2,
        page_size: 4,
        options: [total_entries: 130]
      }
      page =
        Post
        |> Post.published
        |> Scrivener.paginate(config)
```
I'm not sure if that would be useful for your use case. You can find more info here: https://github.com/drewolson/scrivener_ecto/pull/42

**Comment by drewolson** [comment]
@brandonparsons's mentioned work around should be sufficient for now. You can also pass `total_entries: ...` directly to the `paginate` call.

I'm going to close this issue for now.

**Comment by tschmidleithner** [comment]
Hello,

I had the same problem as @brandonparsons and therefore I forked your repo to implement optional prefix support which you can find [here](https://github.com/tschmidleithner/scrivener_ecto). `prefix` is a string that can be added to the options in config, in the same way as with `total_entries`.

I am rather new to Elixir and Phoenix at all, therefore I guess that my code should be improved and refactored before using it. Anyone interested in reviewing my code to improve it?

**Comment by drewolson** [comment]
@tschmidleithner I like this approach and would accept a PR that was cleaned up a bit. I'll reopen this issue for now.
