### ISSUE TITLE
Pass options to `Repo.all`?

### ISSUE THREAD

**Issue by padde** [mojotech/scrivener_ecto#48]
Hi, I'd like to increase the database timeout for a specific query that needs to be paginated, which can be achieved in Ecto by passing `timeout: value` to `Repo.all`. Is there a way to pass ecto repo options to scrivener_ecto? Looking at the source code it seems not. I could look into implementing this feature but it would be nice if you could point me in the right direction first. For example, I am not sure if changes need to be made in the scrivener base repo as well.

At the moment the following options are supported by ecto Repo.all/Repo.one:

* https://hexdocs.pm/ecto/Ecto.Repo.html#module-shared-options
* https://hexdocs.pm/ecto/Ecto.Repo.html#c:all/2-options

Thanks for your consideration!

**Comment by drewolson** [comment]
@padde sorry for the (very) slow reply. [Scrivener.Config](https://github.com/drewolson/scrivener/blob/a2751b00d4d86c9e394934e6a2013b82fe122efc/lib/scrivener/config.ex#L10-L12) does support passing arbitrary options via the `:options` keyword. You'd then need to update `Scrivener.Ecto` to take advantage of these new options.

**Comment by pinksynth** [comment]
@drewolson Would you be open to a pull request that enables this `Repo.all` pass-through? I would also like to have it due to the `timeout: value` option (we use that a lot), and think it wouldn't be too challenging to implement. Thanks!

**Comment by drewolson** [comment]
Sure, a PR would be welcome.

**Comment by ak-14** [comment]
@pinksynth @drewolson any update on this? This feature would be very useful when working with custom default_options and prepare_query callbacks.
