### ISSUE TITLE
Does not work with OTP releases

### ISSUE THREAD

**Issue by stevegraham** [mojotech/scrivener_ecto#6]
Scrivener Ecto doesn't work with OTP releases because it doesn't include Scrivener in its applications of included_applications properties. I fixed it in my project by adding Scrivener to my included_applications.

**Comment by drewolson** [comment]
Thanks for opening this issue. It seems that I could include scrivener in `applications` rather than `included_applications`, correct? The entries in `included_applications` can only be used a single time across an application, which seems overly restrictive.
