### ISSUE TITLE
Wrong count number when using joins and preload

### ISSUE THREAD

**Issue by dokicro** [mojotech/scrivener_ecto#66]
Hi,

I have two models: Page that has many PageLanguages.

Query preload looks like:

```
page
|> join(:left, [p], _ in assoc(p, :languages))
|> preload([_, languages], [languages: languages])
```

The problem is if I have for example 10 posts with the languages I will get `total_entries: 20` but result should be 10. I think we need some DISTINCT option to solve this problem, or I am doing something wrong?

**Comment by astjohn** [comment]
This might be related to #44 and my pull request #45, which may have been prematurely closed...
Perhaps we're all missing something on how to handle joins properly?

**Comment by drewolson** [comment]
The SQL query itself returns 20 entries. This just happens to manifest as 10 entities because of how ecto handles associations. Scrivener operates on the actual number of results returned from the query (via `subquery`), not the number of "top level entities" returned.
