### ISSUE TITLE
Page number greater than total_pages should be allowed

### ISSUE THREAD

**Issue by nicksanders** [mojotech/scrivener_ecto#68]
The pull request below breaks a number of clients we have that increment the page until the entries array is empty. 

https://github.com/drewolson/scrivener_ecto/pull/43/files

Would you be open to a pull request making this configurable?

**Comment by speeddragon** [comment]
Same here. Some endpoints just sent the list of items, other send the total pages, current page, etc. I will convert now all to return total pages, current page, etc.

**Comment by drewolson** [comment]
I'm not interested in allowing pagination beyond the end of the collection. See #71 for a proposed solution.
