### ISSUE TITLE
2.0.0 Wrong pagination results postgres

### ISSUE THREAD

**Issue by marinakr** [mojotech/scrivener_ecto#69]
I had updated phoenix ecto, so scrivener_ecto also was updated to 2.0.0
mix.exs 
`{:scrivener_ecto, "~> 2.0.0"},`

code call pagination
```
Division
    |> select([d], d)
    |> where([d], d.id in ^ids)
    |> join(:inner, [d], l in assoc(d, :legal_entity))
    |> join(:inner, [..., l], e in Employee,
      on:
        e.legal_entity_id == l.id and e.employee_type in [@type_owner, @type_pharmacy_owner] and
          e.is_active
    )
    |> join(:inner, [..., e], innm in assoc(e, :party))
    |> preload([..., l, e, p], legal_entity: {l, employees: {e, party: p}})
    |> preload([:addresses])
    |> Repo.paginate(Map.take(params, ~w(page page_size)a) |> IO.inspect())
```
I added` IO.inspect` just to ensure page is `2`
Output:  
`%{page: 2}`

Result: 
`{:ok, %Scrivener.Page{entries: [%Core.Replica.Division{ .... }], page_number: 1, page_size: 10, total_entries: 1, total_pages: 1}}`

So the problem is I receive **page_number: 1**, when `%{page: 2} ` was set
Also I got same wrong result when call   `|> Repo.paginate(page: 2)` according to doc

**Comment by marinakr** [comment]
The problem scrivener_ecto returns last existing page instead of empty page

**Comment by drewolson** [comment]
I'm not interested in allowing pagination beyond the end of the collection. See #71 for a proposed solution.
