### ISSUE TITLE
module Scrivener.Config is not available in production env

### ISSUE THREAD

**Issue by feixionglee** [mojotech/scrivener_ecto#7]
(UndefinedFunctionError) function Scrivener.Config.new/3 is undefined (module Scrivener.Config is not available)

Scrivener.Config.new(MyApp.Repo, [page_size: 2], %{})
(myapp) lib/myapp/repo.ex:5: Myapp.Repo.paginate/2

my app name is elixirer,

lib/elixirer/repo.ex

```
defmodule Elixirer.Repo do
    use Ecto.Repo, otp_app: :elixir
    use Scrivener, page_size: 2
end

```

mix.exs

```
 defp deps do
    [{:phoenix, "~> 1.2.0"},
     {:phoenix_pubsub, "~> 1.0.0"},
     {:postgrex, ">= 0.0.0"},
     {:phoenix_ecto, "~> 3.0"},
     {:phoenix_html, "~> 2.4"},
     {:phoenix_live_reload, "~> 1.0", only: :dev},
     {:gettext, "~> 0.9"},
     {:cowboy, "~> 1.0"},
     {:comeonin, "~> 2.0"},
     {:qiniu,"~> 0.3.3"},
     {:earmark, "~> 0.2"},
     {:scrivener_ecto, "~> 1.0"},
     {:scrivener_html, "~> 1.1"},
     {:tirexs, "~> 0.8"},
     {:scrivener_elasticsearch, git: "https://github.com/feixionglee/scrivener_elasticsearch.git"},
     {:edeliver, "~> 1.4.0"},
     # {:exrm, ">= 0.16.0", warn_missing: false},
     {:distillery, "~> 0.9"}
    ]
  end
```

**Comment by drewolson** [comment]
I'm assuming you resolved this?

**Comment by feixionglee** [comment]
nope， I try to resolve it, but I need try more hard. do you have any tips? I do not know if it's deployment bug

**Comment by drewolson** [comment]
What is the version of `scrivener_ecto` in your lockfile? Version `1.0.1` introduced a fix around production / releases.

**Comment by feixionglee** [comment]
it's exactly 1.0.1

"scrivener": {:hex, :scrivener, "2.0.0", "38e59a1c37e989c40a22c019da245a86b257182aee45a074292c9038fab39678", [:mix], []},
  "scrivener_ecto": {:hex, :scrivener_ecto, "1.0.1", "013ff84d3bf1a29ecc5cead9808c2433c4cc5531333249cb0186454d06e817c3", [:mix], [{:ecto, "~> 2.0", [hex: :ecto, optional: false]}, {:postgrex, "~> 0.11.2", [hex: :postgrex, optional: true]}, {:scrivener, "~> 2.0", [hex: :scrivener, optional: false]}]},

**Comment by drewolson** [comment]
@bitwalker Sorry to mention you out of the blue, but any ideas on this one? I recently added[1] `scrivener` to `applications` to attempt to fix this problem. Any further ideas? (Feel free to ignore me 😄)

[1] - https://github.com/drewolson/scrivener_ecto/commit/388d72327fb0588484666a93c69a09aed37aa5db

**Comment by bitwalker** [comment]
@feixionglee is `scrivener_ecto` in your applications list? Can you gist your full `mix.exs` file?

**Comment by feixionglee** [comment]
my mix.exs

```
 def application do
    [mod: {Elixirer, []},
     applications: [:phoenix, :phoenix_pubsub, :phoenix_html, :cowboy, :logger, :gettext,
                    :phoenix_ecto, :postgrex, :comeonin, :qiniu, :tirexs, :edeliver]]
  end

```

I will try to add scrivener_ecto into the list, wait me seconds

**Comment by feixionglee** [comment]
It works, thanks you guys very much. 👍

**Comment by feixionglee** [comment]
we should put this tips in README

**Comment by drewolson** [comment]
@feixionglee adding in https://github.com/drewolson/scrivener_ecto/commit/3331aea543fb8282b89c314cedcf4166ba67f05a
