### ISSUE TITLE
`distinct on` requires a subquery for counting 

### ISSUE THREAD

**Issue by tarzan** [mojotech/scrivener_ecto#72]
This is probably an oversight in #64, but queries that have an DISTINCT ON clause (postgresql only) can not be counted on without a `group_by`. They need to be counted through a subquery.

I'll try the write a test for this...

**Comment by tarzan** [comment]
got a fix in #73 

Let me know what you think!

**Comment by drewolson** [comment]
Merged #73, thanks!
