### ISSUE TITLE
Scrivener automatically adjust the page numbers yielding wrong results

### ISSUE THREAD

**Issue by strzibny** [mojotech/scrivener_ecto#74]
If let's say the last page number is 99, then page 100 will simply return the page 99. That's IMHO really wrong. I pass the page number from API and the page 100 need to return 0 results.

```
|> Repo.paginate(page: page_number)
```
Is there a way how to turn this off? Would you accept a patch that cancel this behaviour and point me in the direction where should this be changed in code?

Thank you.

**Comment by drewolson** [comment]
See the `allow_overflow_page_number` option [here](https://github.com/drewolson/scrivener_ecto/blob/e3efdca0b663c1cacd24120b54255727c634e6cc/lib/scrivener/paginater/ecto/query.ex#L20).

**Comment by strzibny** [comment]
Perfect thanks!
