### ISSUE TITLE
Cannot work with multiple databases

### ISSUE THREAD

**Issue by Spadavecchia** [mojotech/scrivener_ecto#81]
The library doesn't pass the options to the repo call. When working with multiple databases, it is necessary to pass the `prefix` options when calling `Repo.all`, `Repo.one`, etc.

**Comment by hkrutzer** [comment]
You can [set the prefix on the query](https://hexdocs.pm/ecto/Ecto.Query.html#module-query-prefix)

**Comment by Spadavecchia** [comment]
Can I? Where? Calls to Repo.all, Repo.one, etc are managed internally by the library.

**Comment by hkrutzer** [comment]
You can `Map.put(query, :prefix, "prefix_name")` or 
```elixir
from u in User,
  prefix: "accounts",
  join: p in assoc(u, :posts),
  prefix: "public"
```
if you know it at compile-time.

**Comment by Spadavecchia** [comment]
It works flawless. Thank you.
