### ISSUE TITLE
total_entries performance

### ISSUE THREAD

**Issue by nlap** [mojotech/scrivener_ecto#9]
Any reason the DISTINCT needs to be a part of the total_entries count? The primary key will be unique.

`select([m], count(field(m, ^primary_key), :distinct))`

It really kills performance versus a count() without distinct

**Comment by nlap** [comment]
Now that I think about it the distinct can be needed with joins. But it does slow things down a lot on single-table queries (adds seconds for me).

I've forked this and implemented my own total_entries/2 for my project. I had to use postgres-specific count estimates to get good performance (~1ms).

For cases like mine where the count is the bottleneck it would be nice to have more control here. If I made this part of the library extensible with a behavior or protocol (keeping the default count with no changes to the API) is that something you'd accept a PR for?

**Comment by drewolson** [comment]
@nlap yes, you're correct that joins would be a problem. At this point, I'd suggest creating a new elixir project that implements the `Scrivener.Paginator` protocol. When you like what you have (and can use it to solve your problems), let me know here. We can either pull it in to `scrivener_ecto` directly or make in another option that we link to from the [Scrivener](https://github.com/drewolson/scrivener) page.

**Comment by joshuataylor** [comment]
@nlap Great, but the only problem with this approach is that the pagination breaks:

Master:

```
total_entries: 82, total_pages: 2
```

Your branch:

```
total_entries: 0, total_pages: 0
```

This is something we also want to look into, as selecting from a single table (ie a materialized view) takes longer than expected.

BTW, for others wanting to test this branch, you can either update your mix.exs for referencing another git repo or test by using a patch file (to see if it fixes your issue). I recommend the mix.exs method.

Patch way (works 2016-10-09):
1) cd deps/scrivener_ecto
2) `wget https://github.com/nlap/scrivener_ecto/commit/a1674d0b57cb5aa5c506f2f0f6f202e5ccc2cb7d.patch`
3) `patch -p1 < a1674d0b57cb5aa5c506f2f0f6f202e5ccc2cb7d.patch`

**Comment by nlap** [comment]
Thanks for the input @joshuataylor.

I'm using my branch directly in my own project for now, so it's not set up to work outside of a Postgres environment (but it is way faster if you are). It would need some work before I would do a PR here, along the lines of @drewolson's suggested approach.

The pagination is working in my environment. You're running postgres, and this query works directly?

`SELECT reltuples::INTEGER AS c FROM pg_class WHERE relname = 'table_name';`

**Comment by joshuataylor** [comment]
@nlap 
Yes, using postgres.

Yes, the query works directly which is weird - I thought perhaps this was happening because it was a materialized view.

This isn't working in testing - so maybe we need to do something postgres related, maybe `vacuum analyze` or something?

**Comment by nlap** [comment]
Yeah, try ANALYZE on your view. I just made a test view that was returning 0 from pg_class until I analyzed it.

Otherwise, does the output from the Ecto query look like this?

`{:ok,
 %Postgrex.Result{columns: ["c"], command: :select, connection_id: 75281,
  num_rows: 1, rows: [[978262]]}}`

I'm doing a kind of hacky `q.rows |> hd |> hd` that might need to be changed

**Comment by drewolson** [comment]
62681ff73954846370ee41047d0a349c530b3d8b should fix this.
