### ISSUE TITLE
UNION queries fail

### ISSUE THREAD

**Issue by iguberman** [mojotech/scrivener_ecto#99]
`Repo.paginate(query, pagination_params)`  fails with the following error:
```
 ** (Postgrex.Error) ERROR 42601 (syntax_error) each UNION query must have the same number of columns
     
         query: SELECT count('*') FROM ....  (any UNION query here)
```     
This happens to a large variety of UNION queries.   I'll provide some examples if necessary but I don't think it matters what specific query, it's just UNION queries in general.  Probably need similar `aggregate` treatment as`group_bys`  

I'm submitting this issue while attempting a fix on my end in the meanwhile.

**Comment by cpjolicoeur** [comment]
[fixed by #98]
